In [42]:
import numpy as np
from datetime import date, timedelta

# 1. Create a 3x3x3 array with random values

In [2]:
arr=np.random.rand(3,3,3)
arr

array([[[0.92870871, 0.0419024 , 0.15647189],
        [0.51169488, 0.54805716, 0.58946757],
        [0.36054576, 0.40053961, 0.12636206]],

       [[0.02157692, 0.83565734, 0.34133748],
        [0.81588749, 0.22828445, 0.14931741],
        [0.64882882, 0.13500891, 0.69473098]],

       [[0.31146874, 0.9362774 , 0.32524461],
        [0.66182311, 0.28075983, 0.82675434],
        [0.57355748, 0.65143136, 0.14944883]]])

# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
arr1 = np.diag(np.arange(4)+1, k = -1)
arr1

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [19]:
n = 8

list_0_1 = [ [ 0, 1], [ 1, 0] ]
rep=4

checkerboard = np.tile( list_0_1, (4,4) ) 

print( checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [25]:
arr3=np.random.rand(5,5)
arr_norm=arr3/ np.linalg.norm(arr3)

arr_norm

array([[0.18535834, 0.10848605, 0.17356425, 0.01512455, 0.30807423],
       [0.28196514, 0.05948251, 0.14582255, 0.26669203, 0.22755007],
       [0.08824341, 0.05642095, 0.31430434, 0.05526334, 0.25633998],
       [0.01132048, 0.04498889, 0.23271962, 0.15171332, 0.17807697],
       [0.09219616, 0.14806196, 0.3428235 , 0.22069064, 0.33938808]])

# 5. How to find common values between two arrays

In [38]:
arr3=np.random.randint(0,5,5)
arr4=np.random.randint(0,5,5)
np.intersect1d(arr3,arr4)

array([3, 4])

# 6. How to get the dates of yesterday, today and tomorrow?¶

In [50]:
yesterday=np.datetime64('today','D')-np.timedelta64(1,'D')
today=np.datetime64('today','D')
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print('Today:-',today)
print('Yesterday:-',yesterday)
print('Tomorrow:-',tomorrow)

Today:- 2020-07-29
Yesterday:- 2020-07-28
Tomorrow:- 2020-07-30


# 7. Consider two random array A and B, check if they are equal

In [52]:
arr3=np.random.randint(0,5,5)
arr4=np.random.randint(0,5,5)
print('Array1',arr3)
print('Array2',arr4)
np.array_equal(arr3,arr4)

Array1 [0 0 1 1 4]
Array2 [1 0 3 0 1]


False

# 8. Create random vector of size 10 and replace the maximum value by 0

In [56]:
arr5=np.random.rand(10)
print('Before:-',arr5)
arr5[arr5.argmax()]=0
print('after:-',arr5)


Before:- [0.59959115 0.61426898 0.73636389 0.4866789  0.50905561 0.29183839
 0.23853901 0.87906435 0.2991892  0.74718284]
after:- [0.59959115 0.61426898 0.73636389 0.4866789  0.50905561 0.29183839
 0.23853901 0.         0.2991892  0.74718284]


# 9. How to print all the values of an array?

In [58]:

arr7 = np.array([1,2,3,4,5,6,7,8,9])
for index, ele in enumerate(arr7):
    print(f"{ele} is at index {index}")

1 is at index 0
2 is at index 1
3 is at index 2
4 is at index 3
5 is at index 4
6 is at index 5
7 is at index 6
8 is at index 7
9 is at index 8


# 10.Subtract the mean of each row of a matrix

In [65]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])


a - a.mean(axis=1, keepdims=True).astype(int)

array([[ 2,  2, -3],
       [ 3,  3, -4],
       [ 1, -1,  2],
       [ 0,  0,  0],
       [-2, -3,  5]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [66]:
arr = np.ones(10)
I = np.random.randint(0,len(arr),20)
arr += np.bincount(I, minlength=len(arr))
print(arr)

[3. 4. 3. 3. 5. 2. 2. 4. 1. 3.]


# 12.How to get the diagonal of a dot product?

In [67]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.64669147 0.14206538 0.58138896 0.47918994 0.38641911]
 [0.44046495 0.40475733 0.44225404 0.03012328 0.77600531]
 [0.55095838 0.3810734  0.52926578 0.9568769  0.17582131]
 [0.11830284 0.86294567 0.07486688 0.82509486 0.83613181]
 [0.07539491 0.01140079 0.04842057 0.35712271 0.66569338]]
[[0.01138961 0.10791777 0.9010131  0.79487876 0.81146098]
 [0.64027806 0.62477951 0.14550751 0.5702159  0.0651125 ]
 [0.31341257 0.21706577 0.52695039 0.42710838 0.98263043]
 [0.14045149 0.7484116  0.78884039 0.73039662 0.84561834]
 [0.55619038 0.05686271 0.88672457 0.31441695 0.56039187]]
diagonal of a dot product method 1 is.... [0.56276705 0.46308667 1.74149479 1.48361854 0.78454055]
diagonal of a dot product method 2 is.... [0.56276705 0.46308667 1.74149479 1.48361854 0.78454055]


# 13.How to find the most frequent value in an array?

In [68]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[4 7 3 9 2 3 8 7 1 5 9 3 0 6 2 3 4 8 9 8 5 2 7 5 9 0 9 8 6 2 0 5 3 2 3 6 4
 1 3 1 4 8 8 2 2 7 2 1 2 7]
2


# 14.How to get the n largest values of an array

In [69]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])


[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [70]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
